import {Injectable} from '@angular/core';
import {HttpManager} from "../utils/HttpManager";
import {Deserializer} from "../utils/Deserializer";
import {ARTResource, ARTURIResource, ARTNode} from "../utils/ARTResources";
import {FormEntry, CustomRangeType} from "../utils/CustomRanges";

@Injectable()
export class CustomRangeServices {

    private serviceName = "CustomRanges";
    private oldTypeService = false;

    constructor(private httpMgr: HttpManager) { }

    /**
     * Returns the description of a reified resource, object of a predicate with custom range
     * @param predicate predicate of which the resource represents the object
     * @param resource object of a predicate with a custom range.
     * @return 
     */
    getReifiedResourceDescription(predicate: ARTURIResource, resource: ARTNode) {
        console.log("[CustomRangeServices] getReifiedResourceDescription");
        var params: any = {
            predicate: predicate.getURI(),
            resource: resource.getNominalValue()
        };
        return this.httpMgr.doGet(this.serviceName, "getReifiedResourceDescription", params, this.oldTypeService);
    }
    
    /**
     * Removes the reified resource generated by means of a custom range
     * @param predicate predicate of wich the resource represents the object
     * @param resource object of a predicate with a custom range
     * @return 
     */
    removeReifiedResource(subject: ARTResource, predicate: ARTURIResource, resource: ARTNode) {
        console.log("[CustomRangeServices] removeReifiedResource");
        var params: any = {
            subject: subject.getNominalValue(),
            predicate: predicate.getURI(),
            resource: resource.getNominalValue()
        };
        return this.httpMgr.doGet(this.serviceName, "removeReifiedResource", params, this.oldTypeService);
    }
    
    /**
     * Returns the form for the given CustomRangeEntry
     * @param creId id of a CustomRangeEntry
     * @return an array of FormEntry
     */
    getCustomRangeEntryForm(creId: string) {
        console.log("[CustomRangeServices] getCustomRangeEntryForm");
        var params: any = {
            id: creId
        };
        return this.httpMgr.doGet(this.serviceName, "getCustomRangeEntryForm", params, this.oldTypeService).map(
            stResp => {
                var form: Array<FormEntry> = [];
                var formEntryElemColl: Array<Element> = stResp.getElementsByTagName("formEntry");
                for (var i = 0; i < formEntryElemColl.length; i++) {
                    var placeholderId = formEntryElemColl[i].getAttribute("placeholderId");
                    var type: CustomRangeType = formEntryElemColl[i].getAttribute("type") == "graph" ? "graph" : "node";
                    var mandatory = formEntryElemColl[i].getAttribute("mandatory") == "true";
                    var userPrompt = formEntryElemColl[i].getAttribute("userPrompt");
                    var converter = formEntryElemColl[i].getElementsByTagName("converter")[0].getAttribute("uri");
                    var entry = new FormEntry(placeholderId, type, mandatory, userPrompt, converter);
                    form.push(entry);
                }
                return form;
            }
        );
    }
}